### ISSUE TITLE
Chunk Generation

### ISSUE THREAD

**Issue by xEchoes** [FreeSoccerHDX/DeepDark#1]
Every single time a chunk is generated after changing world height and minimum y-value, this error spams the console for every chunk generated. Any help?
[23:48:14 ERROR]: Could not pass event ChunkLoadEvent to DeepDark v2.4.3
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by FreeSoccerHDX** [comment]
A change of the world height and minY will always need you to restart the Server and also to delete the world-folder.

**Comment by xEchoes** [comment]
I did that, and it still gives me the same error message.

**Comment by FreeSoccerHDX** [comment]
New update should fix this.
